namespace StaapWinUI
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();

        void NewButton_Click(
            Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void NewSplitButton_Click(
            Object sender,
            Microsoft.UI.Xaml.Controls.SplitButtonClickEventArgs args);
        void PickButton_Click(
            Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void FilterBox_TextChanged(
            Object sender,
            Microsoft.UI.Xaml.Controls.TextChangedEventArgs args);
        void Roster_SelectionChanged(
            Object sender,
            Microsoft.UI.Xaml.Controls.SelectionChangedEventArgs args);
        void HistoryExpander_Expanding(
            Object sender,
            Microsoft.UI.Xaml.Controls.ExpanderExpandingEventArgs args);
        void HistoryExpander_Collapsed(
            Object sender,
            Microsoft.UI.Xaml.Controls.ExpanderCollapsedEventArgs args);
        void SidebarThumb_DragDelta(
            Object sender,
            Microsoft.UI.Xaml.Controls.Primitives.DragDeltaEventArgs args);
        void SidebarThumb_KeyDown(
            Object sender,
            Microsoft.UI.Xaml.Input.KeyRoutedEventArgs args);
        void RootGrid_KeyDown(
            Object sender,
            Microsoft.UI.Xaml.Input.KeyRoutedEventArgs args);
        void TermBox_PreviewKeyDown(
            Object sender,
            Microsoft.UI.Xaml.Input.KeyRoutedEventArgs args);
    }
}
